import 'package:cloud_firestore/cloud_firestore.dart';

/// Trip QR Code generated by the driver for each trip/timeslot
class TripQR {
  final String id;
  final String busId;
  final String busNumber;
  final String driverId;
  final String driverName;
  final String routeId;
  final String routeName;
  final DateTime travelDate;
  final String timeSlot;
  final String qrCode; // Unique QR code for this trip
  final DateTime createdAt;
  final DateTime expiresAt; // QR expires after the trip time
  final bool isActive;
  final List<String> scannedByUsers; // List of user IDs who scanned this QR

  TripQR({
    required this.id,
    required this.busId,
    required this.busNumber,
    required this.driverId,
    required this.driverName,
    required this.routeId,
    required this.routeName,
    required this.travelDate,
    required this.timeSlot,
    required this.qrCode,
    required this.createdAt,
    required this.expiresAt,
    this.isActive = true,
    this.scannedByUsers = const [],
  });

  factory TripQR.fromMap(Map<String, dynamic> map, String id) {
    return TripQR(
      id: id,
      busId: map['busId'] ?? '',
      busNumber: map['busNumber'] ?? '',
      driverId: map['driverId'] ?? '',
      driverName: map['driverName'] ?? '',
      routeId: map['routeId'] ?? '',
      routeName: map['routeName'] ?? '',
      travelDate: (map['travelDate'] as Timestamp?)?.toDate() ?? DateTime.now(),
      timeSlot: map['timeSlot'] ?? '',
      qrCode: map['qrCode'] ?? '',
      createdAt: (map['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      expiresAt: (map['expiresAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      isActive: map['isActive'] ?? true,
      scannedByUsers: List<String>.from(map['scannedByUsers'] ?? []),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'busId': busId,
      'busNumber': busNumber,
      'driverId': driverId,
      'driverName': driverName,
      'routeId': routeId,
      'routeName': routeName,
      'travelDate': Timestamp.fromDate(travelDate),
      'timeSlot': timeSlot,
      'qrCode': qrCode,
      'createdAt': Timestamp.fromDate(createdAt),
      'expiresAt': Timestamp.fromDate(expiresAt),
      'isActive': isActive,
      'scannedByUsers': scannedByUsers,
    };
  }

  TripQR copyWith({
    String? id,
    String? busId,
    String? busNumber,
    String? driverId,
    String? driverName,
    String? routeId,
    String? routeName,
    DateTime? travelDate,
    String? timeSlot,
    String? qrCode,
    DateTime? createdAt,
    DateTime? expiresAt,
    bool? isActive,
    List<String>? scannedByUsers,
  }) {
    return TripQR(
      id: id ?? this.id,
      busId: busId ?? this.busId,
      busNumber: busNumber ?? this.busNumber,
      driverId: driverId ?? this.driverId,
      driverName: driverName ?? this.driverName,
      routeId: routeId ?? this.routeId,
      routeName: routeName ?? this.routeName,
      travelDate: travelDate ?? this.travelDate,
      timeSlot: timeSlot ?? this.timeSlot,
      qrCode: qrCode ?? this.qrCode,
      createdAt: createdAt ?? this.createdAt,
      expiresAt: expiresAt ?? this.expiresAt,
      isActive: isActive ?? this.isActive,
      scannedByUsers: scannedByUsers ?? this.scannedByUsers,
    );
  }

  bool get isExpired => DateTime.now().isAfter(expiresAt);
  
  int get scannedCount => scannedByUsers.length;
}
